CREATE TABLE ContactRequests (
    RequestId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(254) NOT NULL,
    Service NVARCHAR(150) NULL,
    Message NVARCHAR(MAX) NOT NULL,
    SubmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
